# Generated by Django 4.1 on 2023-11-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('palavras_chave', models.CharField(max_length=100)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='artigos/')),
                ('publicado', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
